"""tables

Revision ID: aa3c1c7940e5
Revises: 
Create Date: 2024-05-22 15:07:23.944794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3c1c7940e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psikologlar',
    sa.Column('ps_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad', sa.String(length=50), nullable=False),
    sa.Column('soyad', sa.String(length=50), nullable=False),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=10), nullable=True),
    sa.Column('fotograf', sa.String(), nullable=True),
    sa.Column('adres', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefonNo', sa.String(length=15), nullable=True),
    sa.Column('mezun_oldugu_okul', sa.String(length=100), nullable=True),
    sa.Column('aldığı_egitimler', sa.String(), nullable=True),
    sa.Column('muayenehane_adresi', sa.String(length=255), nullable=True),
    sa.Column('randevu_tarihleri', sa.String(), nullable=True),
    sa.Column('calisma_saatleri', sa.String(), nullable=True),
    sa.Column('tc_kimlik_no', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('ps_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefonNo')
    )
    with op.batch_alter_table('psikologlar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psikologlar_tc_kimlik_no'), ['tc_kimlik_no'], unique=True)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('tc_kimlik_no', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('ad', sa.String(length=64), nullable=True),
    sa.Column('soyad', sa.String(length=64), nullable=True),
    sa.Column('telefon', sa.String(length=11), nullable=True),
    sa.Column('adres', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_tc_kimlik_no'), ['tc_kimlik_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('randevu',
    sa.Column('randevu_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('psikolog_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('saat', sa.String(length=5), nullable=False),
    sa.Column('mesaj', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['psikolog_id'], ['psikologlar.ps_id'], ),
    sa.PrimaryKeyConstraint('randevu_id')
    )
    op.create_table('ucretler',
    sa.Column('ucret_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ucret_miktari', sa.Float(), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('ps_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ps_id'], ['psikologlar.ps_id'], ),
    sa.PrimaryKeyConstraint('ucret_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ucretler')
    op.drop_table('randevu')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tc_kimlik_no'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('psikologlar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psikologlar_tc_kimlik_no'))

    op.drop_table('psikologlar')
    # ### end Alembic commands ###
